# Generated by Django 2.2.6 on 2019-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=30)),
                ('course_tool', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
