# Generated by Django 2.2.6 on 2019-11-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
