# Generated by Django 2.2.6 on 2019-11-21 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_tool', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='referred_by',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tool'),
        ),
    ]
