# Generated by Django 2.2.6 on 2019-11-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191120_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referred_by',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
