# Generated by Django 2.2.6 on 2019-11-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_student_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tools',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
